const countries = [
  { country: "United States", code: "+1", flag: "🇺🇸" },
  { country: "Canada", code: "+1", flag: "🇨🇦" },
  { country: "United Kingdom", code: "+44", flag: "🇬🇧" },
  { country: "Australia", code: "+61", flag: "🇦🇺" },
  { country: "India", code: "+91", flag: "🇮🇳" },
  { country: "Germany", code: "+49", flag: "🇩🇪" },
  { country: "France", code: "+33", flag: "🇫🇷" },
  { country: "Brazil", code: "+55", flag: "🇧🇷" },
  { country: "China", code: "+86", flag: "🇨🇳" },
  { country: "Japan", code: "+81", flag: "🇯🇵" },
  { country: "South Korea", code: "+82", flag: "🇰🇷" },
  { country: "Mexico", code: "+52", flag: "🇲🇽" },
  { country: "Russia", code: "+7", flag: "🇷🇺" },
  { country: "South Africa", code: "+27", flag: "🇿🇦" },
  { country: "Nigeria", code: "+234", flag: "🇳🇬" },
  { country: "Egypt", code: "+20", flag: "🇪🇬" },
  { country: "Saudi Arabia", code: "+966", flag: "🇸🇦" },
  { country: "United Arab Emirates", code: "+971", flag: "🇦🇪" },
  { country: "Turkey", code: "+90", flag: "🇹🇷" },
  { country: "Greece", code: "+30", flag: "🇬🇷" },
  { country: "Italy", code: "+39", flag: "🇮🇹" },
  { country: "Spain", code: "+34", flag: "🇪🇸" },
  { country: "Portugal", code: "+351", flag: "🇵🇹" },
  { country: "Argentina", code: "+54", flag: "🇦🇷" },
  { country: "Chile", code: "+56", flag: "🇨🇱" },
  { country: "Peru", code: "+51", flag: "🇵🇪" },
  { country: "Colombia", code: "+57", flag: "🇨🇴" },
  { country: "Venezuela", code: "+58", flag: "🇻🇪" },
  { country: "Pakistan", code: "+92", flag: "🇵🇰" },
  { country: "Bangladesh", code: "+880", flag: "🇧🇩" },
  { country: "Sri Lanka", code: "+94", flag: "🇱🇰" },
  { country: "Thailand", code: "+66", flag: "🇹🇭" },
  { country: "Vietnam", code: "+84", flag: "🇻🇳" },
  { country: "Philippines", code: "+63", flag: "🇵🇭" },
  { country: "Indonesia", code: "+62", flag: "🇮🇩" },
  { country: "Netherlands", code: "+31", flag: "🇳🇱" },
  { country: "Belgium", code: "+32", flag: "🇧🇪" },
  { country: "Sweden", code: "+46", flag: "🇸🇪" },
  { country: "Norway", code: "+47", flag: "🇳🇴" },
  { country: "Denmark", code: "+45", flag: "🇩🇰" },
  { country: "Finland", code: "+358", flag: "🇫🇮" },
  { country: "Switzerland", code: "+41", flag: "🇨🇭" },
  { country: "Austria", code: "+43", flag: "🇦🇹" },
];

export default countries;
